---
spring:
  profiles: dev
  application:
      name: micro-config-tian-dev
---
spring:
  profiles: test
  application:
      name: micro-config-tian-test
---
spring:
  profiles:
    active: ${spring.profiles}
